
package com.rojecservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RojecService", targetNamespace = "http://service.rojecservice.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RojecService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.rojecservice.com/RojecService/processRequest", output = "http://service.rojecservice.com/RojecService/processResponse")
    public void process(
        @WebParam(name = "arg0", partName = "arg0")
        ServiceTunnel arg0);

}
