
package com.rojecservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RojecServiceImplService", targetNamespace = "http://service.rojecservice.com/", wsdlLocation = "http://localhost:8888/rojec?wsdl")
public class RojecServiceImplService
    extends Service
{

    private final static URL ROJECSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROJECSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ROJECSERVICEIMPLSERVICE_QNAME = new QName("http://service.rojecservice.com/", "RojecServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/rojec?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROJECSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ROJECSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RojecServiceImplService() {
        super(__getWsdlLocation(), ROJECSERVICEIMPLSERVICE_QNAME);
    }

    public RojecServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROJECSERVICEIMPLSERVICE_QNAME, features);
    }

    public RojecServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ROJECSERVICEIMPLSERVICE_QNAME);
    }

    public RojecServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROJECSERVICEIMPLSERVICE_QNAME, features);
    }

    public RojecServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RojecServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RojecService
     */
    @WebEndpoint(name = "RojecServiceImplPort")
    public RojecService getRojecServiceImplPort() {
        return super.getPort(new QName("http://service.rojecservice.com/", "RojecServiceImplPort"), RojecService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RojecService
     */
    @WebEndpoint(name = "RojecServiceImplPort")
    public RojecService getRojecServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.rojecservice.com/", "RojecServiceImplPort"), RojecService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROJECSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ROJECSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ROJECSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
